/****** Object:  StoredProcedure [dbo].[pa_CAR_FIN_TRANSACTION_Load]    Script Date: 19/09/2024 04:06:41 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO







ALTER PROCEDURE [dbo].[pa_CAR_FIN_TRANSACTION_Load]  AS

DECLARE @fedesde DATETIME

--SET @fedesde = CASE WHEN CAST( DATEADD(HH,-24, GETDATE()) AS DATE) < '2023-07-01' 
--					THEN '2023-07-01' 
--					ELSE CAST( DATEADD(HH,-24, GETDATE()) AS DATE) 
--					END

 SET @fedesde = '2024-09-12'  

--PAGOS A CUENTA
SELECT DISTINCT
pjl.AXXDOCPAYMCOLLECTORID ,  
pjl.TRANSACTIONDATE ,	 	
hea.JOURNALBATCHNUMBER , 	
pjl.CURRENCYCODE  , 
'COORIGEN' = 1  ,
hea.DESCRIPTION 
INTO #PAGOSACUENTA
FROM  dbo.CustomerPaymentJournalHeaderStaging hea 

INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl
ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
 
WHERE --pjl.PAYMENTREFERENCE = ''
	PJL.VOUCHER NOT LIKE '%CLIE%'
AND pjl.FBMJournalName <> 'INTERCO'
AND hea.JOURNALNAME LIKE '%COBI%'  
--AND hea.JOURNALNAME NOT LIKE '%COBIN%' 
--AND HEA.JOURNALBATCHNUMBER IN ('CONT4-000293329') 
AND pjl.CREDITAMOUNT > 0
AND pjl.DEBITAMOUNT = 0
AND pjl.TRANSACTIONDATE >= @fedesde
AND hea.ISPOSTED = 1
AND NOT EXISTS( SELECT PJLL.JOURNALBATCHNUMBER, SUM(PJLL.CREDITAMOUNT), SUM(PJLL.DEBITAMOUNT) FROM CUSTOMERPAYMENTJOURNALLINESTAGING AS PJLL
				INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging AROO  ON PJLL.FBMLEDGERJOURNALTRANSRECID = AROO.PAYMENTTRANSRECID  
				WHERE PJLL.JOURNALBATCHNUMBER = PJL.JOURNALBATCHNUMBER
				AND AROO.TENDERTYPEID IN ('78','95','96')
				GROUP BY PJLL.JOURNALBATCHNUMBER
				having SUM(PJLL.CREDITAMOUNT) = SUM(PJLL.DEBITAMOUNT)
				)


--COBRO INVERTIDO
SELECT DISTINCT
pjl.AXXDOCPAYMCOLLECTORID ,  
pjl.TRANSACTIONDATE ,	 
'FBMTERMINALID' = ''  ,
hea.JOURNALBATCHNUMBER , 
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
pjl.CURRENCYCODE  , 
'COORIGEN' = 3 ,
hea.DESCRIPTION  ,
'TRANSACTIONNUMBER' = '',
'STAFF' = '',
'CUSTOMERWORKER' =   '' 
INTO #COBROINVERTIDO
FROM dbo.CustomerPaymentJournalHeaderStaging hea  

INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl
ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 

INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro
ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID

WHERE  pjl.FBMJournalName <> 'INTERCO'
--AND pjl.PAYMENTREFERENCE = ''
AND PJL.VOUCHER NOT LIKE '%CLIE%'
AND pjl.TRANSACTIONDATE >= @fedesde
--AND HEA.JOURNALBATCHNUMBER IN ('CONT4-000314054','CONT4-000314164') 
AND pjl.DEBITAMOUNT > 0
AND pjl.CREDITAMOUNT = 0
AND hea.ISPOSTED = 1
AND 
(
	hea.JOURNALNAME LIKE '%COBIN%'  
	OR
	(
		hea.JOURNALNAME LIKE '%COBI%'  
		AND 
		hea.JOURNALNAME NOT LIKE '%COBIN%'
		AND 
		pjl.JOURNALBATCHNUMBER NOT IN  --CASOS DONDE SE REGISTRA EN DIARIO DE PAGO A CUENTA
		(
			SELECT JOURNALBATCHNUMBER FROM #PAGOSACUENTA
		)
	)
)
AND NOT EXISTS( SELECT PJLL.JOURNALBATCHNUMBER, SUM(PJLL.CREDITAMOUNT), SUM(PJLL.DEBITAMOUNT) FROM CUSTOMERPAYMENTJOURNALLINESTAGING AS PJLL
				INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging AROO  ON PJLL.FBMLEDGERJOURNALTRANSRECID = AROO.PAYMENTTRANSRECID  
				WHERE PJLL.JOURNALBATCHNUMBER = PJL.JOURNALBATCHNUMBER
				AND AROO.TENDERTYPEID IN ('78','95','96')
				GROUP BY PJLL.JOURNALBATCHNUMBER
				having SUM(PJLL.CREDITAMOUNT) = SUM(PJLL.DEBITAMOUNT)
				)

--ARMO CONSULTA FINAL

--PAGO A CUENTA
SELECT 
AXXDOCPAYMCOLLECTORID ,  
TRANSACTIONDATE ,	 
'FBMTERMINALID' = '' ,
JOURNALBATCHNUMBER , 
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
CURRENCYCODE  , 
'COORIGEN' = 1  ,
DESCRIPTION ,
'TRANSACTIONNUMBER' = '',
'STAFF' = '' ,
'CUSTOMERWORKER' =   '' 
, 'FEAZURE' = GETDATE()
FROM #PAGOSACUENTA


UNION


--EXTRACTO DE CAJA
SELECT DISTINCT
pjl.AXXDOCPAYMCOLLECTORID ,  
pjl.TRANSACTIONDATE ,	 
'FBMTERMINALID' = ''  ,
hea.JOURNALBATCHNUMBER , 
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
pjl.CURRENCYCODE  , 
'COORIGEN' = 2 ,
hea.DESCRIPTION  ,
'TRANSACTIONNUMBER' = '',
'STAFF' = '' ,
'CUSTOMERWORKER' =   '' 
, 'FEAZURE' = GETDATE()

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl
ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 

INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro
ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID

WHERE 
pjl.TRANSACTIONTEXT  LIKE '%extracto%'
AND pjl.FBMJournalName <> 'INTERCO'
AND pjl.DEBITAMOUNT > 0
AND pjl.TRANSACTIONDATE >= @fedesde
AND hea.ISPOSTED = 1


UNION


--COBRO INVERTIDO
SELECT DISTINCT
AXXDOCPAYMCOLLECTORID ,  
TRANSACTIONDATE ,	 
'FBMTERMINALID' = ''  ,
JOURNALBATCHNUMBER , 
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
CURRENCYCODE  , 
'COORIGEN' = 3 ,
DESCRIPTION  ,
'TRANSACTIONNUMBER' = '',
'STAFF' = '',
'CUSTOMERWORKER' =   '' 
,'FEAZURE' = GETDATE()

FROM #COBROINVERTIDO
  

UNION

--CANJE DE VALOR
SELECT DISTINCT
pjl.AXXDOCPAYMCOLLECTORID ,  
pjl.TRANSACTIONDATE ,	 
'FBMTERMINALID' = ''  ,
hea.JOURNALBATCHNUMBER , 
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
pjl.CURRENCYCODE  , 
'COORIGEN' = 4 ,
hea.DESCRIPTION  ,
'TRANSACTIONNUMBER' = '',
'STAFF' = '' ,
'CUSTOMERWORKER' =   '' 
,'FEAZURE' = GETDATE()

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl
ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 

INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro
ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID

INNER JOIN dbo.FBMComTYLedgerJournalTransStaging let
ON pjl.FBMTYVALUESEQNUM = let.TYVALUESEQNUM 
AND pjl.JOURNALBATCHNUMBER = let.JOURNALNUM  

WHERE  pjl.FBMJournalName <> 'INTERCO'
AND pjl.DEBITAMOUNT > 0
AND pjl.TRANSACTIONDATE >= @fedesde
AND hea.ISPOSTED = 1
--AND HEA.JOURNALBATCHNUMBER IN ('CONT4-000277709')
--AND let.FBMCOMTYSTATUS = 7 --(Canjeado)
AND 
(
	hea.JOURNALNAME LIKE '%CVD%'
	AND let.FBMCOMTYSTATUS = 7 --(Canjeado)
	--AND pjl.TRANSACTIONDATE >= @fedesde
	OR
	(
		PJL.VOUCHER LIKE '%COBI%'
		AND ARO.TENDERTYPEID = '78'-- Efectivo
		--AND HEA.JOURNALBATCHNUMBER IN ('CONT4-000277391', 'CONT4-000288419')
		AND 
		NOT EXISTS  --CASOS DONDE SE REGISTRA EN DIARIO DE PAGO A CUENTA
		(
			SELECT JOURNALBATCHNUMBER FROM #PAGOSACUENTA AS PC WHERE PC.JOURNALBATCHNUMBER = HEA.JOURNALBATCHNUMBER
		)
		AND 
		NOT EXISTS  --CASOS DONDE SE REGISTRA EN DIARIO DE COBRO INVERTIDO
		(
			SELECT JOURNALBATCHNUMBER FROM #COBROINVERTIDO AS CI WHERE CI.JOURNALBATCHNUMBER = HEA.JOURNALBATCHNUMBER
		)
	)
)

UNION

--Rendicion Caja
SELECT
'AXXDOCPAYMCOLLECTORID' = '' ,
ret.TRANSACTIONDATE , 
'FBMTERMINALID' = ret.BATCHTERMINALID  ,
'JOURNALBATCHNUMBER' = '' ,
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
'CURRENCYCODE' = ret.CURRENCY ,
'COORIGEN' = 5 ,
'DESCRIPTION' = ''  ,
ret.TRANSACTIONNUMBER ,
ret.STAFF ,
'CUSTOMERWORKER' = ISNULL(wok.PHONETICFIRSTNAME , '')
,'FEAZURE' = GETDATE()

FROM RetailTransactionStaging ret

INNER JOIN RetailTransactionSafeTenderTransStaging rts
ON ret.TRANSACTIONNUMBER = rts.TRANSACTIONNUMBER 

OUTER APPLY  
(  
	SELECT TOP 1 PHONETICFIRSTNAME 
	FROM dbo.HcmEmployeeV2Staging  
	WHERE PERSONNELNUMBER = ret.STAFF 
	ORDER BY PERSONNELNUMBER DESC
) wok  

WHERE ret.SALESORDERID = ''
AND ret.transactionType = 17
AND ret.TRANSACTIONDATE  >= @fedesde


UNION


--Punto Flotante
SELECT
'AXXDOCPAYMCOLLECTORID' = '' ,
ret.TRANSACTIONDATE , 
'FBMTERMINALID' = ret.BATCHTERMINALID  ,
'JOURNALBATCHNUMBER' = '' ,
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
'CURRENCYCODE' = ret.CURRENCY ,
'COORIGEN' = 6 ,
'DESCRIPTION' = ''  ,
ret.TRANSACTIONNUMBER  ,
ret.STAFF  ,
'CUSTOMERWORKER' = ISNULL(wok.PHONETICFIRSTNAME , '')
,'FEAZURE' = GETDATE()

FROM RetailTransactionStaging ret

LEFT JOIN RetailTransactionSafeTenderTransStaging rts
ON ret.TRANSACTIONNUMBER = rts.TRANSACTIONNUMBER  

OUTER APPLY  
(  
	SELECT TOP 1 PHONETICFIRSTNAME 
	FROM dbo.HcmEmployeeV2Staging  
	WHERE PERSONNELNUMBER = ret.STAFF 
	ORDER BY PERSONNELNUMBER DESC
) wok  

WHERE ret.SALESORDERID = ''
AND ret.transactionType = 5    --Punto Flotante
 AND ret.TRANSACTIONDATE  >= @fedesde

 



















