/****** Object:  StoredProcedure [dbo].[pa_CAR_FIN_TRANSACTION_Load]    Script Date: 19/09/2024 04:00:52 p.m. ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO



-- exec [dbo].[pa_CAR_FIN_TRANSACTION_Load] 



ALTER PROCEDURE [dbo].[pa_CAR_FIN_TRANSACTION_Load]  AS

exec  [dbo].[pa_CAR_FIN_TENDERTYPE_Valid_Load]  

DECLARE @fedesde DATETIME

--SET @fedesde = CASE WHEN CAST( DATEADD(HH,-24, GETDATE()) AS DATE) < '2023-07-01' 
--					THEN '2023-07-01' 
--					ELSE CAST( DATEADD(HH,-24, GETDATE()) AS DATE) 
--					END

SET @fedesde = '2024-09-10'  

;WITH PAGOSACUENTA AS
(
--PAGOS A CUENTA
SELECT DISTINCT
	pjl.AXXDOCPAYMCOLLECTORID ,  
	pjl.TRANSACTIONDATE ,	 	
	hea.JOURNALBATCHNUMBER , 	
	pjl.CURRENCYCODE  , 
	'COORIGEN' = 1  ,
	hea.DESCRIPTION 

FROM  dbo.CustomerPaymentJournalHeaderStaging hea 
	INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
 
WHERE 	PJL.VOUCHER NOT LIKE '%CLIE%'
	AND pjl.FBMJournalName <> 'INTERCO'
	AND hea.JOURNALNAME LIKE '%COBI%'  
	AND hea.JOURNALNAME NOT LIKE '%COBIN%' -- Agregado 11/09/2024
	--AND hea.JOURNALBATCHNUMBER  in ( 'CONT4-000304599' ,'CONT4-000303989') 
	AND pjl.CREDITAMOUNT > 0
	AND pjl.DEBITAMOUNT = 0
	AND pjl.TRANSACTIONDATE >= @fedesde
	AND hea.ISPOSTED = 1
	AND NOT EXISTS( SELECT PJLL.JOURNALBATCHNUMBER, SUM(PJLL.CREDITAMOUNT), SUM(PJLL.DEBITAMOUNT) FROM CUSTOMERPAYMENTJOURNALLINESTAGING AS PJLL
					WHERE PJLL.JOURNALBATCHNUMBER = PJL.JOURNALBATCHNUMBER
					GROUP BY PJLL.JOURNALBATCHNUMBER
					having SUM(PJLL.CREDITAMOUNT) = SUM(PJLL.DEBITAMOUNT)
					)
	),
 COBROINVERTIDO AS
(
--COBRO INVERTIDO
SELECT DISTINCT
	pjl.AXXDOCPAYMCOLLECTORID ,  
	pjl.TRANSACTIONDATE ,	 
	'FBMTERMINALID' = ''  ,
	hea.JOURNALBATCHNUMBER , 
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	pjl.CURRENCYCODE  , 
	'COORIGEN' = (CASE WHEN hea.DESCRIPTION like '%invertido%' THEN 3 ELSE 1 END) ,-- 3 ,  cambiado 11/9/2024
	hea.DESCRIPTION  ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '',
	'CUSTOMERWORKER' =   '' 

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

	INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
	INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID
	INNER JOIN dbo.JournalTenderTypeValid JTTV ON hea.JOURNALBATCHNUMBER = JTTV.JournalNum ---- CV no U$S agregado 26/6/2024

WHERE  pjl.FBMJournalName <> 'INTERCO'
	AND PJL.VOUCHER NOT LIKE '%CLIE%'
	AND pjl.TRANSACTIONDATE >= @fedesde
	--AND pjl.DEBITAMOUNT > 0	-- comentado 12/07/2024
	--AND pjl.CREDITAMOUNT = 0	-- comentado 12/07/2024
	AND hea.ISPOSTED = 1
	AND 
	( 
		(hea.JOURNALNAME LIKE '%COBIN%'  
			OR (hea.JOURNALNAME LIKE '%COBI%' 	
				AND  hea.JOURNALNAME NOT LIKE '%COBIN%'
				AND pjl.JOURNALBATCHNUMBER NOT IN (SELECT JOURNALBATCHNUMBER FROM PAGOSACUENTA)--CASOS DONDE SE REGISTRA EN DIARIO DE PAGO A CUENTA
				)
		)
		OR  ---- CV no U$S agregado 26/6/2024
			(hea.JOURNALNAME LIKE '%CVD%' AND JTTV.JournalType = 'OTHERS')

	AND NOT EXISTS ( SELECT PJLL.JOURNALBATCHNUMBER, SUM(PJLL.CREDITAMOUNT), SUM(PJLL.DEBITAMOUNT) 
					FROM CUSTOMERPAYMENTJOURNALLINESTAGING AS PJLL
						INNER JOIN dbo.CustomerPaymentJournalHeaderStaging heas on heas.JOURNALBATCHNUMBER = pjll.JOURNALBATCHNUMBER --  agregado 26/6/2024
					WHERE PJLL.JOURNALBATCHNUMBER = PJL.JOURNALBATCHNUMBER AND heas.JOURNALNAME LIKE '%COBIN%' --  agregado 26/6/2024
					GROUP BY PJLL.JOURNALBATCHNUMBER
					having SUM(PJLL.CREDITAMOUNT) = SUM(PJLL.DEBITAMOUNT)
					)
	) 
---------------------------------------------------------------------------------  AGREGADO 28/08/2024
UNION

SELECT DISTINCT
	pjl.AXXDOCPAYMCOLLECTORID ,  
	pjl.TRANSACTIONDATE ,	 
	'FBMTERMINALID' = ''  ,
	JOURNALBATCHNUMBER = CONCAT(hea.JOURNALBATCHNUMBER , '-'),
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	pjl.CURRENCYCODE  , 
	'COORIGEN' = 3 ,
	hea.DESCRIPTION  ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '',
	'CUSTOMERWORKER' =   '' 

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

	INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
	INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID
	INNER JOIN dbo.JournalTenderTypeValid JTTV ON hea.JOURNALBATCHNUMBER = JTTV.JournalNum ---- CV no U$S agregado 26/6/2024

WHERE  pjl.FBMJournalName <> 'INTERCO'
	AND PJL.VOUCHER NOT LIKE '%CLIE%'
	AND pjl.TRANSACTIONDATE >= @fedesde
	--AND pjl.DEBITAMOUNT > 0
	--AND pjl.CREDITAMOUNT = 0
	AND hea.ISPOSTED = 1
	AND hea.DESCRIPTION NOT like '%invertido%' -- agregado 11/9/2024
	AND 
	( 
		(hea.JOURNALNAME LIKE '%COBIN%'  
			OR (hea.JOURNALNAME LIKE '%COBI%' 	
				AND  hea.JOURNALNAME NOT LIKE '%COBIN%'
				AND pjl.JOURNALBATCHNUMBER NOT IN (SELECT JOURNALBATCHNUMBER FROM PAGOSACUENTA)--CASOS DONDE SE REGISTRA EN DIARIO DE PAGO A CUENTA
				)
		)
		OR  ---- CV no U$S agregado 26/6/2024
			(hea.JOURNALNAME LIKE '%CVD%' AND JTTV.JournalType = 'OTHERS')

	AND NOT EXISTS ( SELECT PJLL.JOURNALBATCHNUMBER, SUM(PJLL.CREDITAMOUNT), SUM(PJLL.DEBITAMOUNT) 
					FROM CUSTOMERPAYMENTJOURNALLINESTAGING AS PJLL
						INNER JOIN dbo.CustomerPaymentJournalHeaderStaging heas on heas.JOURNALBATCHNUMBER = pjll.JOURNALBATCHNUMBER --  agregado 26/6/2024
					WHERE PJLL.JOURNALBATCHNUMBER = PJL.JOURNALBATCHNUMBER AND heas.JOURNALNAME LIKE '%COBIN%' --  agregado 26/6/2024
					GROUP BY PJLL.JOURNALBATCHNUMBER
					having SUM(PJLL.CREDITAMOUNT) = SUM(PJLL.DEBITAMOUNT)
					)
	)
---------------------------------------------------------------------------------	FIN AGREGADO	
)


--ARMO CONSULTA FINAL

--PAGO A CUENTA
SELECT 
	AXXDOCPAYMCOLLECTORID ,  
	TRANSACTIONDATE ,	 
	'FBMTERMINALID' = '' ,
	JOURNALBATCHNUMBER , 
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	CURRENCYCODE  , 
	'COORIGEN' = 1  ,
	DESCRIPTION ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '' ,
	'CUSTOMERWORKER' =   '' 
	, 'FEAZURE' = GETDATE()
FROM PAGOSACUENTA


UNION


--EXTRACTO DE CAJA
SELECT DISTINCT
	pjl.AXXDOCPAYMCOLLECTORID ,  
	pjl.TRANSACTIONDATE ,	 
	'FBMTERMINALID' = ''  ,
	hea.JOURNALBATCHNUMBER , 
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	pjl.CURRENCYCODE  , 
	'COORIGEN' = 2 ,
	hea.DESCRIPTION  ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '' ,
	'CUSTOMERWORKER' =   '' 
	, 'FEAZURE' = GETDATE()

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

	INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
	INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID

WHERE 
	pjl.TRANSACTIONTEXT  LIKE '%extracto%'
	AND pjl.FBMJournalName <> 'INTERCO'
	AND pjl.DEBITAMOUNT > 0
	AND pjl.TRANSACTIONDATE >= @fedesde
	AND hea.ISPOSTED = 1


UNION


--COBRO INVERTIDO
SELECT DISTINCT
	AXXDOCPAYMCOLLECTORID ,  
	TRANSACTIONDATE ,	 
	'FBMTERMINALID' = ''  ,
	JOURNALBATCHNUMBER , 
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	CURRENCYCODE  , 
	COORIGEN ,--'COORIGEN' = 3 ,
	DESCRIPTION  ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '',
	'CUSTOMERWORKER' =   '' 
	,'FEAZURE' = GETDATE()

FROM COBROINVERTIDO
  

UNION

--CANJE DE VALOR
	SELECT DISTINCT
	pjl.AXXDOCPAYMCOLLECTORID ,  
	pjl.TRANSACTIONDATE ,	 
	'FBMTERMINALID' = ''  ,
	hea.JOURNALBATCHNUMBER , 
	'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
	pjl.CURRENCYCODE  , 
	'COORIGEN' = 4 ,
	hea.DESCRIPTION  ,
	'TRANSACTIONNUMBER' = '',
	'STAFF' = '' ,
	'CUSTOMERWORKER' =   '' 
	,'FEAZURE' = GETDATE()

FROM dbo.CustomerPaymentJournalHeaderStaging hea  

	INNER JOIN dbo.CustomerPaymentJournalLineStaging pjl ON hea.JOURNALBATCHNUMBER = pjl.JOURNALBATCHNUMBER 
	INNER JOIN dbo.AxxComRetailOrderPaymentInfoStaging aro ON pjl.FBMLEDGERJOURNALTRANSRECID = aro.PAYMENTTRANSRECID
	INNER JOIN dbo.FBMComTYLedgerJournalTransStaging let ON pjl.FBMTYVALUESEQNUM = let.TYVALUESEQNUM AND pjl.JOURNALBATCHNUMBER = let.JOURNALNUM 
	INNER JOIN dbo.JournalTenderTypeValid JTTV ON hea.JOURNALBATCHNUMBER = JTTV.JournalNum ---- CV U$S agregado 26/6/2024 

WHERE  pjl.FBMJournalName <> 'INTERCO'
	AND pjl.DEBITAMOUNT > 0
	AND pjl.TRANSACTIONDATE >= @fedesde
	AND hea.ISPOSTED = 1
	--AND hea.JOURNALBATCHNUMBER  in ( 'CONT4-000304599' ,'CONT4-000303989')
	AND JTTV.JournalType = 'CV_USD'
	-- AND
	--(
	--	hea.JOURNALNAME LIKE '%CVD%'
	--	AND let.FBMCOMTYSTATUS = 7 --(Canjeado)
	--	OR
	--	(
	--		--PJL.VOUCHER LIKE '%COBI%'
	--		--AND ARO.TENDERTYPEID = '78'-- Efectivo
	AND NOT EXISTS  --CASOS DONDE SE REGISTRA EN DIARIO DE PAGO A CUENTA
				(SELECT JOURNALBATCHNUMBER FROM PAGOSACUENTA AS PC WHERE PC.JOURNALBATCHNUMBER = HEA.JOURNALBATCHNUMBER)
	AND NOT EXISTS  --CASOS DONDE SE REGISTRA EN DIARIO DE COBRO INVERTIDO
				(SELECT JOURNALBATCHNUMBER FROM COBROINVERTIDO AS CI WHERE CI.JOURNALBATCHNUMBER = HEA.JOURNALBATCHNUMBER)
	--	)
	--)

UNION

--Rendicion Caja
SELECT
'AXXDOCPAYMCOLLECTORID' = '' ,
ret.TRANSACTIONDATE , 
'FBMTERMINALID' = ret.BATCHTERMINALID  ,
'JOURNALBATCHNUMBER' = '' ,
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
'CURRENCYCODE' = ret.CURRENCY ,
'COORIGEN' = 5 ,
'DESCRIPTION' = ''  ,
ret.TRANSACTIONNUMBER ,
ret.STAFF ,
'CUSTOMERWORKER' = ISNULL(wok.PHONETICFIRSTNAME , '')
,'FEAZURE' = GETDATE()

FROM RetailTransactionStaging ret

INNER JOIN RetailTransactionSafeTenderTransStaging rts
ON ret.TRANSACTIONNUMBER = rts.TRANSACTIONNUMBER 

OUTER APPLY  
(  
	SELECT TOP 1 PHONETICFIRSTNAME 
	FROM dbo.HcmEmployeeV2Staging  
	WHERE PERSONNELNUMBER = ret.STAFF 
	ORDER BY PERSONNELNUMBER DESC
) wok  

WHERE ret.SALESORDERID = ''
AND ret.transactionType = 17
AND ret.TRANSACTIONDATE  >= @fedesde


UNION


--Punto Flotante
SELECT
'AXXDOCPAYMCOLLECTORID' = '' ,
ret.TRANSACTIONDATE , 
'FBMTERMINALID' = ret.BATCHTERMINALID  ,
'JOURNALBATCHNUMBER' = '' ,
'ORDERRESPONSIBLEPERSONNELNUMBER' = '' ,
'CURRENCYCODE' = ret.CURRENCY ,
'COORIGEN' = 6 ,
'DESCRIPTION' = ''  ,
ret.TRANSACTIONNUMBER  ,
ret.STAFF  ,
'CUSTOMERWORKER' = ISNULL(wok.PHONETICFIRSTNAME , '')
,'FEAZURE' = GETDATE()

FROM RetailTransactionStaging ret

LEFT JOIN RetailTransactionSafeTenderTransStaging rts
ON ret.TRANSACTIONNUMBER = rts.TRANSACTIONNUMBER  

OUTER APPLY  
(  
	SELECT TOP 1 PHONETICFIRSTNAME 
	FROM dbo.HcmEmployeeV2Staging  
	WHERE PERSONNELNUMBER = ret.STAFF 
	ORDER BY PERSONNELNUMBER DESC
) wok  

WHERE ret.SALESORDERID = ''
AND ret.transactionType = 5    --Punto Flotante
 AND ret.TRANSACTIONDATE  >= @fedesde













